# Generated by Django 4.2.5 on 2023-09-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='Description',
            field=models.TextField(),
        ),
    ]
